const projects = [
  {
    id: "0101",
    name: "Coconut",
    photo: {
      image1: "img/image/CocoNoam/1.JPG",
      image2: "img/image/CocoNoam/2.JPG",
      image3: "img/image/CocoNoam/3.JPG",
      image4: "img/image/CocoNoam/4.JPG",
      image5: "img/image/CocoNoam/5.JPG",
      image6: "img/image/CocoNoam/6.PNG",
      image7: "img/image/CocoNoam/7.JPG",
      image8: "img/image/CocoNoam/8.JPG",
      image9: "img/image/CocoNoam/9.JPG",
      image10: "img/image/CocoNoam/10.JPG",
      image11: "img/image/CocoNoam/11.JPG",
      image12: "img/image/CocoNoam/12.JPG",
      image13: "img/image/CocoNoam/13.JPG",
      image13: "img/image/CocoNoam/14.JPG",
      image15: "img/image/CocoNoam/15.JPG",
      image16: "img/image/CocoNoam/16.JPG",
      image17: "img/image/CocoNoam/17.JPG",
      image18: "img/image/CocoNoam/18.JPG",
      image19: "img/image/CocoNoam/19.JPG",
      image20: "img/image/CocoNoam/4a348dd1-7c54-402e-b3a2-30725d2439b1.JPG",
    },
  },
  {
    id: "0102",
    name: "Department",
    photo: {
      image1: "img/image/Department/1.JPG",
      image2: "img/image/Department/2.JPG",
      image3: "img/image/Department/3.JPG",
      image4: "img/image/Department/4.JPG",
      image5: "img/image/Department/5.JPG",
      image6: "img/image/Department/6.JPG",
      image7: "img/image/Department/7.JPG",
      image8: "img/image/Department/8.JPG",
      image9: "img/image/Department/9.JPG",
      image10: "img/image/Department/10.JPG",
      image11: "img/image/Department/11.JPG",
      image12: "img/image/Department/12.JPG",
      image13: "img/image/Department/13.JPG",
      image14: "img/image/Department/14.JPG",
      image15: "img/image/Department/15.JPG",
      image16: "img/image/Department/16.JPG",
      image17: "img/image/Department/17.JPG",
      image18: "img/image/Department/18.JPG",
      image19: "img/image/Department/19.JPG",
      image20: "img/image/Department/20.JPG",
      image21: "img/image/Department/21.JPG",
      image22: "img/image/Department/22.JPG",
      image23: "img/image/Department/23.JPG",
      image24: "img/image/Department/24.JPG",
      image25: "img/image/Department/25 (2).JPG",
      image26: "img/image/Department/26.JPG",
      image27: "img/image/Department/27.JPG",
      image28: "img/image/Department/28.JPG",
      image29: "img/image/Department/29.JPG",
      image30: "img/image/Department/30.JPG",
      image31: "img/image/Department/31.JPG",
      image32: "img/image/Department/32.JPG",
      image33: "img/image/Department/33.JPG",
      image34: "img/image/Department/34.JPG",
      image35: "img/image/Department/35.JPG",
      image36: "img/image/Department/36.JPG",
    },
  },
  {
    id: "0103",
    name: "di project",
    photo: {
      image1: "img/image/di project/0ED66DE7-8A41-472C-8C9E-7977196F1445.JPG",
      image2: "img/image/di project/DSCF4884.jpg",
      image3: "img/image/di project/DSCF4899.JPEG",
      image4: "img/image/di project/DSCF4949.JPEG",
      image5: "img/image/di project/DSCF4980.JPEG",
      image6: "img/image/di project/DSCF5010.JPG",
      image7: "img/image/di project/DSCF5333.JPG",
      image8: "img/image/di project/DSCF5517.JPEG",
      image9: "img/image/di project/DSCF6515.JPEG",
      image10: "img/image/di project/DSCF6936.JPEG",
      image11: "img/image/di project/IMG_0527 (1).JPG",
      image12: "img/image/di project/IMG_0528 (1).JPG",
      image13: "img/image/di project/IMG_0529.JPG",
      image14: "img/image/di project/IMG_0533.JPG",
      image15: "img/image/di project/IMG_0542.JPG",
      image16: "img/image/di project/IMG_0544.JPG",
      image17: "img/image/di project/IMG_0545.JPG",
      image18: "img/image/di project/IMG_0548.JPG",
      image19: "img/image/di project/IMG_0546.JPG",
      image20: "img/image/di project/IMG_0550.JPG",
      image21: "img/image/di project/IMG_0556.JPG",
      image22: "img/image/di project/IMG_0558.JPG",
      image23: "img/image/di project/IMG_0560.JPG",
      image24: "img/image/di project/IMG_0565.JPG",
      image25: "img/image/di project/IMG_0566.JPG",
      image26: "img/image/di project/IMG_0570.PNG",
      image27: "img/image/di project/IMG_0574.PNG",
      image28: "img/image/di project/IMG_0599.PNG",
      image29: "img/image/di project/photo 07-07-2024, 8 05 45 pm (17).JPG",
      image30: "img/image/di project/photo 07-07-2024, 8 20 29 pm (1).JPG",
      image31: "img/image/di project/photo 07-07-2024, 8 20 29 pm (14).JPG",
      image32: "img/image/di project/photo 07-07-2024, 8 20 29 pm (2).JPG",
    },
  },
  {
    id: "0104",
    name: "ofer",
    photo: {
      image1: "img/image/9 עופר/New Element 13.MP4",
    },
  },
  {
    id: "0105",
    name: "HumanDivinity",
    photo: {
      image1: "/img/image/HumanDivinity/1.JPG",
      image2: "/img/image/HumanDivinity/2.JPG",
      image3: "/img/image/HumanDivinity/3.JPG",
      image4: "/img/image/HumanDivinity/4.JPG",
      image5: "/img/image/HumanDivinity/5.JPG",
      image6: "/img/image/HumanDivinity/6.JPG",
      image7: "/img/image/HumanDivinity/7.JPG",
      image8: "/img/image/HumanDivinity/8.JPG",
      image9: "/img/image/HumanDivinity/9.JPG",
      image10: "/img/image/HumanDivinity/10.JPG",
      image11: "/img/image/HumanDivinity/11.JPG",
      image12: "/img/image/HumanDivinity/12.JPG",
      image13: "/img/image/HumanDivinity/13.JPG",
      image14: "/img/image/HumanDivinity/14.JPG",
      image15: "/img/image/HumanDivinity/15.JPG",
      image16: "/img/image/HumanDivinity/16.JPG",
      image17: "/img/image/HumanDivinity/17.JPG",
      image18: "/img/image/HumanDivinity/18.JPG",
      image19: "/img/image/HumanDivinity/19.JPG",
    },
  },
  {
    id: "0106",
    name: "LookBook",
    photo: {
      image1: "/img/image/LookBook/1.JPG",
      image2: "/img/image/LookBook/2.JPG",
      image3: "/img/image/LookBook/3 videp.MP4",
      image4: "/img/image/LookBook/4.PNG",
      image5: "/img/image/LookBook/5.PNG",
      image6: "/img/image/LookBook/6.PNG",
      image7: "/img/image/LookBook/7 video.MP4",
      image8: "/img/image/LookBook/8 video.MP4",
      image9: "/img/image/LookBook/9.JPG",
      image10: "/img/image/LookBook/10.JPG",
      image11: "/img/image/LookBook/11.PNG",
      image12: "/img/image/LookBook/12.PNG",
      image13: "/img/image/LookBook/13.PNG",
      image14: "/img/image/LookBook/14.MP4",
      image15: "/img/image/LookBook/15.PNG",
      image16: "/img/image/LookBook/16 gif.MP4",
      image17: "/img/image/LookBook/17.PNG",
      image18: "/img/image/LookBook/18.PNG",
      image19: "/img/image/LookBook/19 videp.MP4",
      image20: "/img/image/LookBook/20 video.MP4",
      image21: "/img/image/LookBook/21.PNG",
      image22: "/img/image/LookBook/22.PNG",
      image23: "/img/image/LookBook/23.PNG",
      image24: "/img/image/LookBook/24.PNG",
      image25: "/img/image/LookBook/25.PNG",
      image26: "/img/image/LookBook/26.PNG",
      image27: "/img/image/LookBook/27.PNG",
      image28: "/img/image/LookBook/28.PNG",
      image29: "/img/image/LookBook/29.PNG",
      image30: "/img/image/LookBook/30.MP4",
      image31: "/img/image/LookBook/31.PNG",
      image32: "/img/image/LookBook/32.PNG",
    },
  },
  {
    id: "0107",
    name: "MuyriProduction",
    photo: {
      image1: "/img/image/MuyriProduction/1.JPG",
      image2: "/img/image/MuyriProduction/2.JPG",
      image3: "/img/image/MuyriProduction/3.JPG",
      image4: "/img/image/MuyriProduction/4.JPG",
      image5: "/img/image/MuyriProduction/5.JPG",
      image6: "/img/image/MuyriProduction/6.JPG",
      image7: "/img/image/MuyriProduction/7.JPG",
      image8: "/img/image/MuyriProduction/8.JPG",
      image9: "/img/image/MuyriProduction/9.JPG",
      image10: "/img/image/MuyriProduction/10.JPG",
      image11: "/img/image/MuyriProduction/11.JPG",
      image12: "/img/image/MuyriProduction/12.JPG",
      image13: "/img/image/MuyriProduction/13.mp4",
      image14: "/img/image/MuyriProduction/14.PNG",
    },
  },
  {
    id: "0108",
    name: "NYC",
    photo: {
      image1: "/img/image/NYC/1.JPG",
      image2: "/img/image/NYC/2.jpg",
      image3: "/img/image/NYC/3.JPEG",
      image4: "/img/image/NYC/4.JPG",
      image5: "/img/image/NYC/5.JPG",
      image6: "/img/image/NYC/6.JPEG",
      image7: "/img/image/NYC/7.JPEG",
      image8: "/img/image/NYC/8.JPG",
      image9: "/img/image/NYC/9.JPEG",
      image10: "/img/image/NYC/10.JPEG",
      image11: "/img/image/NYC/11.JPEG",
      image12: "/img/image/NYC/12.JPEG",
    },
  },
  {
    id: "0109",
    name: "packsh",
    photo: {
      image1: "/img/image/packsh/1.JPG",
      image2: "/img/image/packsh/2.JPG",
      image3: "/img/image/packsh/3.JPG",
      image4: "/img/image/packsh/4.JPG",
      image5: "/img/image/packsh/5.jpg",
      image6: "/img/image/packsh/6.JPG",
      image7: "/img/image/packsh/7.JPG",
      image8: "/img/image/packsh/8.JPG",
      image9: "/img/image/packsh/9.JPG",
    },
  },
  {
    id: "01010",
    name: "roni",
    photo: {
      image1: "/img/image/roni/1.mp4",
      image2: "/img/image/roni/2.jpg",
      image3: "/img/image/roni/3.png",
      image4: "/img/image/roni/4.png",
      image5: "/img/image/roni/5.jpg",
      image6: "/img/image/roni/6.png",
      image7: "/img/image/roni/7.jpg",
      image8: "/img/image/roni/8.jpg",
      image9: "/img/image/roni/9.jpg",
      image10: "/img/image/roni/10.jpg",
      image11: "/img/image/roni/11.jpg",
      image12: "/img/image/roni/12.jpg",
      image13: "/img/image/roni/13.jpg",
      image14: "/img/image/roni/14.jpg",
      image15: "/img/image/roni/15.png",
      image16: "/img/image/roni/16.jpg",
      image17: "/img/image/roni/17.jpg",
      image18: "/img/image/roni/18.jpg",
      image19: "/img/image/roni/19.jpg",
      image20: "/img/image/roni/20.jpg",
      image21: "/img/image/roni/21.jpg",
    },
  },
  {
    id: "01011",
    name: "vogue-coco",
    photo: {
      image1: "/img/image/vogue-coco/1.PNG",
      image2: "/img/image/vogue-coco/2.PNG",
      image3: "/img/image/vogue-coco/3.PNG",
      image4: "/img/image/vogue-coco/4.PNG",
      image5: "/img/image/vogue-coco/5.PNG",
      image6: "/img/image/vogue-coco/6.PNG",
    },
  },
  {
    id: "01012",
    name: "wow-london",
    photo: {
      image1: "/img/image/wow-london/1.JPG",
      image2: "/img/image/wow-london/2.JPG",
      image3: "/img/image/wow-london/4.JPG",
      image4: "/img/image/wow-london/5.JPG",
      image5: "/img/image/wow-london/6.JPG",
      image6: "/img/image/wow-london/7 video.mp4",
      image7: "/img/image/wow-london/8.JPG",
      image8: "/img/image/wow-london/9.JPG",
      image9: "/img/image/wow-london/10.JPG",
      image10: "/img/image/wow-london/11.JPG",
      image11: "/img/image/wow-london/12.JPG",
      image12: "/img/image/wow-london/13.JPG",
      image13: "/img/image/wow-london/14.JPG",
      image14: "/img/image/wow-london/15.JPG",
      image15: "/img/image/wow-london/16.JPG",
      image16: "/img/image/wow-london/17.JPG",
      image17: "/img/image/wow-london/18.JPG",
      image18: "/img/image/wow-london/19.JPG",
      image19: "/img/image/wow-london/3.JPG",
    },
  },
  {
    id: "01013",
    name: "video",
    photo: {
      image1: "/img/image/Video/VID-20241204-WA0092.mp4",
    },
  },
];


export {
    projects
};
